### ISSUE TITLE
AWS SDK Fails to build with OpenSSL1.1

### ISSUE THREAD

**Issue by kmiller15211** [aws/aws-iot-device-sdk-cpp#44]
When building against OpenSSL1.1, the following compile error is seen (this is without quieting deprecated declarations, obviously): 

`/home/kmiller/GitLab/data-management/AWS_SDK/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp: In destructor ‘awsiotsdk::network::OpenSSLInitializer::~OpenSSLInitializer()’:
/home/kmiller/GitLab/data-management/AWS_SDK/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp:45:41: error: ‘void ERR_remove_thread_state(void*)’ is deprecated [-Werror=deprecated-declarations]
             ERR_remove_thread_state(NULL);
                                         ^
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /home/kmiller/GitLab/data-management/AWS_SDK/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.hpp:40,
                 from /home/kmiller/GitLab/data-management/AWS_SDK/aws-iot-device-sdk-cpp/network/OpenSSL/OpenSSLConnection.cpp:25:
/usr/include/openssl/err.h:247:1: note: declared here
 DEPRECATEDIN_1_1_0(void ERR_remove_thread_state(void *))`

Could this call to ERR_remove_thread_state just be simply wrapped in the following to compile with SSL 1.1.0f? 

```
#if OPENSSL_VERSION_NUMBER >= 0x10000000L && OPENSSL_VERSION_NUMBER < 0x10100000L
...
#endif 
```

?

**Comment by kmiller15211** [comment]
Looks to be linked to this issue: https://github.com/aws/aws-iot-device-sdk-cpp/pull/19, which mentions that OpenSsl support would be updated in the next version. This is from June 20th.

**Comment by kmiller15211** [comment]
Actually, the code originally had ERR_remove_state(0);, which was ALSO deprecated in favor of what I printed out above, which is now deprecated. So... a few versions behind here.

**Comment by vareddy** [comment]
The pull request has been merged into master.
